### ISSUE TITLE
PHP Concealing Issue

### ISSUE THREAD

**Issue by marinhero** [hachibu/vim-conceal-operators#1]
If the file starts with `<?php` none of the arrows inside the code will be able to be replaced. If the `<?php` is removed the plugin works fine. It even works if it starts with `<` but in the moment you add the `?` stops working.

**Comment by marinhero** [comment]
Sample:
`   <?php`
 ` `
 `    foreach ($variable as $value) {`
`       echo $value->id;`
`     }`

**Comment by hachibu** [comment]
Thanks @marinhero. I'll look into this!

**Comment by hachibu** [comment]
@marinhero this should be fixed now

**Comment by marinhero** [comment]
tested and it works! thanks @hachibu !
