### ISSUE TITLE
Coffeescript conceal issue

### ISSUE THREAD

**Issue by marinhero** [hachibu/vim-conceal-operators#7]
The `:` character breaks the plugin.
Example:

` define →`
`     {`
`       run: ->` 
`     if read_cookie('last_seen') == null`
`       create_cookie('last_seen', new Date().getTime(), 90)`
` }`

**Comment by hachibu** [comment]
@marinhero thank you for the report. I'll look into this right away!

**Comment by hachibu** [comment]
@marinhero fixed this! just git pull and recompile your rules!

**Comment by marinhero** [comment]
@hachibu it works! Thanks!
